#!/usr/bin/python3
#

# Global Variables (change these if you must)
_log_level_ = 0
_lag_level_ = 0.25
_start_volume_ = 15
_refresh_rate_ = (60 * 5)
_server_port_ = 3145
_config_sep_ = '|-:;:-|'
_server_address_ = '127.0.0.1'
_music_dir_ = '/home/mp3/Music'
_log_file_ = '/home/mp3/mp3.145/mp3145.log'
_persistance_ = '/home/mp3/mp3.145/mp3145.cfg'

#----------------------------------------------------------
#
# DO NOT TOUCH BELOW THIS POINT !!!!!!!!!
#
#----------------------------------------------------------

# Imports
import os 
import random
import pygame
import threading
import socketserver
from time import sleep
import RPi.GPIO as GPIO	
from Adafruit_CharLCD import Adafruit_CharLCD

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(0)
LCD = Adafruit_CharLCD()

# The logger / printer
def dprint(data = ''):
	global _log_file_
	global _log_level_
	if (_log_level_ > 0):
		print(data, end = '')
	if (_log_level_ > 1):
		log_dev = open(_log_file_, 'a')
		print(data, end = '', file = log_dev)
		log_dev.close()
		
# The pygame backend
dprint('Loading music thread...\n')
class musicThread(threading.Thread):
	def __init__(self, music_directory):
		threading.Thread.__init__(self)
		global _start_volume_	
		self.alive = 1
		self.force = -1
		self.shuffle = 1
		self.playing = 0
		self.current = -1
		self.volume = 0.1
		self.previous = -1		
		pygame.mixer.init()
		self.musicdir = music_directory
		self.setVol(2, _start_volume_, 0)
		self.playlist = self.genPlaylist()	
	def writePersist(self):
		global _config_sep_
		data =	str(self.playing) + _config_sep_ + str(self.shuffle) + _config_sep_ + str(self.volume + 0.01) + _config_sep_ + str(self.current) + _config_sep_ + str(self.force)
		global _persistance_
		persist = open(_persistance_, 'w')
		print(data + '\n', end = '', file = persist)
		persist.close()	
	def genPlaylist(self):
		genlist = []
		for root, subdirs, thefiles in os.walk(self.musicdir):
			for name in thefiles:
				if (name[-4:].lower() == '.mp3'):
					genlist.append(os.path.join(root, name))
					dprint('Found: ' + os.path.join(root, name) + '\n')
			for name in subdirs:
				dprint(os.path.join(root, name) + '\n')			
		return sorted(genlist)
	def refreshMusic(self):
		oldcur = self.current
		if (oldcur != -1):
			oldcur = self.playlist[self.current]
		self.playlist = self.genPlaylist()
		if (oldcur != -1):
			for x in range(0, len(self.playlist)):
				if (self.playlist[x] == oldcur): 
					self.current = x
					break					
	def getStatus(self):
		retme = ''
		if (self.playing): retme += 'Playing '
		else: retme +='Stopped on '
		if (self.current != -1): retme += self.getCurrent() + ', '
		else: retme += '?: No Song, '
		if (self.shuffle): retme += 'shuffle is on, '
		else: retme += 'shuffle is off, '
		retme += 'volume is ' + str(int(self.volume*100))
		if (self.force != -1): retme += '. Queued ' + str(self.force) + '/' + str(len(self.playlist)) + ": " + self.cleanName(self.playlist[self.force])
		return retme
	def getList(self):
		return self.playlist
	def getVol(self):
		return str(self.volume * 100)
	def setVol(self, upordown = -1, forcevol = 10, persist = 1):
		newvol = self.volume
		if (upordown == 2):
			newvol = (forcevol / 100)
		elif (upordown == 1):
			newvol += 0.1
		elif (upordown == -1):
			newvol -= 0.1
		if (newvol > 1.0):
			newvol = 1.0
		elif (newvol < 0.0):
			newvol = 0.0
		pygame.mixer.music.set_volume(newvol)
		self.volume = pygame.mixer.music.get_volume()
		if (persist): self.writePersist()
		return str(self.volume * 100)
	def setShuffle(self):
		if (self.shuffle == 0):
			self.shuffle = 1
		else:
			self.shuffle = 0
		self.writePersist()
		return self.shuffle
	def setPlay(self):
		if (self.playing == 0):
			self.playing = 1
			while (pygame.mixer.music.get_busy() != 1):
				sleep(0.1)
			self.writePersist()
			return self.current
		else:
			self.playing = 0
			self.writePersist()
		return self.playing
	def setDie(self):
		self.playing = 0
		self.writePersist()
		sleep(1)
		self.alive = 0
	def setForce(self, force):
		self.force = force
		if (force > 0):
			self.writePersist()
			return self.cleanName(self.playlist[self.force])
	def getCurrentNo(self):
		return self.current
	def getCurrent(self): 
		return str(self.current) + '/' + str(len(self.playlist)) + ': ' + self.cleanName(self.playlist[self.current])
	def playLast(self):
		if (self.shuffle == 1):
			self.setForce(self.previous)
			return self.playNext()
		else:
			self.setForce(self.current - 1)
			return self.playNext()
	def cleanName(self, name = ''): 
		return name[len(self.musicdir)+1:-4].replace(os.sep, ' - ')
	def playNext(self, replay = 0):
		if (replay == 0):
			self.previous = self.current
			if (self.force == -1):
				if (self.shuffle == 1):
					self.current = random.randrange(len(self.playlist))
				else:
					self.current += 1
					if (self.current >= len(self.playlist)):
						self.current = self.current - len(self.playlist)
			else:
				self.current = self.force
				self.force = -1
		
		if (pygame.mixer.music.get_busy()):
			pygame.mixer.music.stop()
		pygame.mixer.music.load(self.playlist[self.current])
		pygame.mixer.music.play()	
		self.writePersist()
		return self.cleanName(self.playlist[self.current])
	def run(self):
		refr = 0
		flag = 0
		initforce = -1
		global _persistance_
		if (os.path.isfile(_persistance_)):
			global _config_sep_
			persist = open(_persistance_, 'r')
			conf = persist.readline()
			persist.close()
			dprint('Persistance: ' + conf)
			values = conf.split(_config_sep_)
			self.playing = int(values[0])
			self.shuffle = int(values[1])
			self.setVol(2, int(float(values[2])*100))
			self.force = int(values[3])
			initforce = int(values[4])
		while (self.alive):
			if ((pygame.mixer.music.get_busy() == 0) and (self.playing == 1)):
				dprint(self.playNext(flag) + '\n')
				if (initforce >= 0):
					self.force = initforce
					initforce = -1
				flag = 0
			elif ((pygame.mixer.music.get_busy() == 1) and (self.playing == 0)):
				pygame.mixer.music.stop()
				flag = 1
			refr += 1
			global _lag_level_
			global _refresh_rate_
			if (refr == ((_refresh_rate_ * (1 / _lag_level_)) +1)):
				self.refreshMusic()
				self.writePersist()
				refr = 0
			sleep(_lag_level_)

dprint('Starting music thread...\n')
music = musicThread(_music_dir_)
music.start()

# Resets and clears the L.C.D.
def resetLCD():
	global LCD
	LCD.begin(16,1)
	LCD.clear()

# Text formatter for the L.C.D.
def lcdify(data, resetScroll = 0, increment = 0):
	if (len(data) <= 16):
		return data
	elif (resetScroll == 1):
		lcdify.counter = -1
		return data[:16]
	else:
		if (lcdify.counter > len(data)):
			lcdify.counter = -1
		elif (resetScroll != 1):
			lcdify.counter += increment
	data += '   '
	poptext = data[:lcdify.counter]
	newtext = data[lcdify.counter+1:] + poptext
	return newtext[:16]

# The LCD communicator
def lcdPrint(data, resetScroll = 0):
	global _music_dir_
	data = data.replace(_music_dir_ + '/', '')
	songbits = data.split(' - ')
	part1 = songbits[len(songbits) - 2]
	part2 = songbits[len(songbits) - 1].replace('.mp3', '')
	try:
		if (int(part1)):
			part2 = part1 + ': ' + part2			
			part1 = songbits[len(songbits) - 3]
	except ValueError:
		pass
	lcdata = lcdify(part1, resetScroll, 1) + '\n' + lcdify(part2, resetScroll, 1)
	if (resetScroll == 1):
		dprint('Resetting LCD: ' + lcdata.replace('\n', ' - ') + '\n')
		resetLCD()
		LCD.message('%s' % ( lcdata ) )
	elif ((len(part1) > 16) or (len(part2) > 16)):
		dprint('Running LCD Scroll: ' + lcdata.replace('\n', ' - ') + '\n') 
		resetLCD()
		LCD.message('%s' % ( lcdata ) )

# LCD thread
class scrollText(threading.Thread):
	global _lag_level_
	def __init__(self):
		threading.Thread.__init__(self)
		self.last = ''
		self.alive = 1
		self.spam = 0
	def setDie(self):
		self.alive = 0
	def run(self):			
		while (self.alive):
			global music
			plist = music.getList()
			current = music.getCurrentNo()
			if ((current == -1) and (self.spam == 0)):
				lcdPrint('mp3.145 - Ready to Rock', 1)
				self.spam = 1
			elif (current >= 0):
				if (self.last != plist[current]):	
					self.last = plist[current]
					lcdPrint(plist[current], 1)
				else:
					lcdPrint(plist[current])
			global _lag_level_
			sleep(_lag_level_)

dprint('Starting LCD thread...\n')
resetLCD()
lcdThread = scrollText()
lcdThread.start()

# The socketserver interface
dprint('Loading TCP server...\n')
class MyTCPHandler(socketserver.BaseRequestHandler):
	def handle(self):
		self.active = 1
		dprint(self.client_address[0] + ' has connected.\n')
		while (self.active):
			global music			
			self.cmd = self.request.recv(1024).strip().decode('utf-8')
			dprint('Command: <' + self.cmd + '> From: [' + self.client_address[0] + ']\n')
			plist = music.getList()
			if (self.cmd == 'h'):				
				dprint('Sending help.\n')
				try:
					self.request.sendall(b'Commands:\n')
					self.request.sendall(b'---------\n')
					self.request.sendall(b'p - play/stop\n')
					self.request.sendall(b'n - skip/next\n')
					self.request.sendall(b'b - back/previous\n')
					self.request.sendall(b'r - random on/off\n')			
					self.request.sendall(b's - search songs\n')
					self.request.sendall(b'f - force song\n')
					self.request.sendall(b'l - list all songs\n')
					self.request.sendall(b'u - volume +10\n')
					self.request.sendall(b'd - volume -10\n')
					self.request.sendall(b'v - custom volume\n')
					self.request.sendall(b'x - exit\n')
				except: 
					dprint('Failed to send help!\n')
			elif (self.cmd == 'r'):
				try:
					if (music.setShuffle()):
						dprint('Random: On.\n')
						self.request.sendall(b'Random: On\n')
					else:
						dprint('Random: Off.\n')
						self.request.sendall(b'Random: Off\n')
				except:
					dprint('Failed to send shuffle/random ACK!\n')
			elif (self.cmd == 'p'):
				try:
					if (music.setPlay()):
						dprint('Play.\n')
						self.request.sendall(b'Play\n')
					else:
						dprint('Stop.\n')
						self.request.sendall(b'Stop\n')
				except:
					dprint('Failed to send play/stop ACK!\n')
			elif (self.cmd == 'n'):
				tmp = music.playNext() + '\n'
				dprint(tmp)
				try:
					self.request.sendall(tmp.encode('utf-8'))
				except:
					dprint('Failed to send next ACK!\n')
			elif (self.cmd == 'c'):
				tmp = music.getStatus() + '\n'
				dprint(tmp)
				try:
					self.request.sendall(tmp.encode('utf-8'))
				except:
					dprint('Failed to send status!\n')
			elif (self.cmd == 'b'):
				tmp = music.playLast() + '\n'
				dprint(tmp)
				try:
					self.request.sendall(tmp.encode('utf-8'))
				except:
					dprint('Failed to send back ACK!\n')
			elif (self.cmd == 'l'):
				dprint('Sending playlist.\n')
				try:
					self.request.sendall(b'<table style="font-size: 30px">')
					for x in range(0, len(plist)):
						self.request.sendall(b'<tr><td align=left>' + str(x).encode('utf-8') + b'</td><td align=left>' + music.cleanName(plist[x]).encode('utf-8') + b'</td></tr>\n')
					self.request.sendall(b'</table>')
					self.request.sendall(b'__END_OF_LIST__\n')
				except:
					dprint('Failed to send playlist\n')
			elif (self.cmd == 's'):
				fff = 0;
				self.request.sendall(b'Search string: \n')
				testme = self.request.recv(1024).strip().decode('utf-8')
				dprint('Searching for: ' + testme + '\n')
				try:
					for x in range(0, len(plist)):
						if (plist[x].lower().find(testme) != -1):
							self.request.sendall(str(x).encode('utf-8') + b': ' + music.cleanName(plist[x]).encode('utf-8') + b'<br>\n')
							fff += 1
					self.request.sendall(b'__END_OF_LIST__\n')
					dprint('Found ' + str(fff) + ' items.\n')
				except:
					dprint('Failed to send search results!\n')
			elif (self.cmd == 'f'):
				forceme = 0
				try:
					self.request.sendall(b'Force song: \n')
					forceme = int(self.request.recv(1024).strip().decode('utf-8'))
					if ((forceme < 0) or (forceme >= len(plist))):
						int('fail')
					dprint(tmp)
					self.request.sendall(tmp.encode('utf-8'))						
				except ValueError:
					dprint('Invalid force: ' + str(forceme))
				except:
					dprint('Failed to send force ACK!\n')
			elif (self.cmd == 'u'):
				tmp = 'Volume: ' + music.setVol(1) + '\n'
				dprint(tmp)
				try:
					self.request.sendall(tmp.encode('utf-8'))
				except:
					dprint('Failed to send volume_up ACK!\n')
			elif (self.cmd == 'd'):
				tmp = 'Volume: ' + music.setVol() + '\n'
				dprint(tmp)
				try:
					self.request.sendall(tmp.encode('utf-8'))
				except:
					dprint('Failed to send volume_down ACK!\n')
			elif (self.cmd == 'v'):
				newvol = 0
				try:
					self.request.sendall(b'New volume (current=' + music.getVol().encode('utf-8') + b') [1-100] : \n')
					newvol = int(self.request.recv(1024).strip().decode('utf-8'))
					if ((newvol < 0) or (newvol > 100)):
						int('fail')
					tmp = 'Volume: ' + str(music.setVol(2, newvol)) + '\n'
					dprint(tmp)
					self.request.sendall(tmp.encode('utf-8'))
				except ValueError:
					dprint('Invalid volume force: ' + str(newvol))
				except: 
					dprint('Failed to send volume_custom ACK!\n')
			elif (self.cmd == 'x'):
				try:
					self.request.sendall(b'Goodbye.\n')
				except:
					dprint('Failed to send exit ACK!\n')
				dprint('Disconnecting ' + self.client_address[0] + '\n')
				self.active = 0
			elif (self.cmd == 'halt'):
				music.setDie()
				sleep(5)
				exit(0)
			else:
				try:
					self.request.sendall(b'Unknown command: ' + self.cmd.encode('utf-8') + b'\n')
				except:
					dprint('Failed to send unknown_command ACK!\n')
# Do-it-to-it			
dprint('Starting TCP server...\n')
server = socketserver.TCPServer((_server_address_, _server_port_), MyTCPHandler)
print('mp3.145 is ready.\n')
server.serve_forever()
music.setDie()
