#!/usr/bin/python3
#

import sys
import socket

cmd = 's\n'

try:
	v = sys.argv[1]
except:
	print('You forgot to input a search string!')
	exit(1)
c = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
c.connect(('127.0.0.1', 3145))
#print('Connected')
#s = c.recv(1024).strip()
#print('Recieved: ' + s.decode('utf-8'))
c.sendall(cmd.encode('utf-8'))
#print('Data sent.')
s = c.recv(1024).strip()
#print('Recieved: ' + s.decode('utf-8'))
#v = input('Search Song: ')
c.sendall(v.encode('utf-8'))
#print('Data sent.')
passes = 0
while (True):
	s = c.recv(4096).strip().decode('utf-8')
	if (not s): break
	x = s.find('__END_OF_LIST__')
	if (x != -1):
		print(s[:x])
		break
	print(s)
	passes += 1
if (passes == 0): print('No results found')
c.sendall(b'x\n')
#print('Shutting down.')
c.close()
